"""Dữ liệu câu trả lời CHUNG theo nhóm tình huống, dùng bởi `gieo_giao_tiep_chung.py`.

Mỗi dòng: (nhóm tình huống, tên tình huống, [các cách khách nói], câu trả lời).

LUẬT KHI THÊM DÒNG - đây là lời AI đọc NGUYÊN VĂN cho khách thật:
- Không con số, lãi suất, phí, hạn mức, điều kiện hay thời hạn của sản phẩm.
- Không hứa việc hệ thống chưa chắc làm được (gửi tin nhắn, gọi lại đúng giờ,
  giảm lãi, duyệt hồ sơ). Chỉ nói "em xin ghi nhận".
- Không trả lời thay chính sách của ngân hàng (người làm tự do có vay được
  không, nợ xấu có được xét không...): những câu đó thuộc tài liệu sản phẩm.
- Tối đa 35 từ, mở đầu "Dạ", kết "ạ".
"""

# Nhóm tình huống của 27 dòng gốc (khai báo trong gieo_giao_tiep_chung.BANG).
NHOM_CUA_DONG_GOC = {
    "Khách cảm ơn": "Xã giao",
    "Khách khen": "Xã giao",
    "Khách hỏi chuyện riêng của tư vấn viên": "Xã giao",
    "Khách muốn suy nghĩ thêm": "Khách phân vân",
    "Khách cần hỏi ý người nhà": "Khách phân vân",
    "Khách chưa có nhu cầu ngay": "Khách phân vân",
    "Khách đang khó khăn tài chính": "Khách phân vân",
    "Khách bảo nói chậm lại": "Trục trặc nghe nói",
    "Khách không nghe rõ": "Trục trặc nghe nói",
    "Khách không hiểu": "Trục trặc nghe nói",
    "Khách bảo chờ một chút": "Trục trặc nghe nói",
    "Khách xin lỗi vì đường truyền": "Trục trặc nghe nói",
    "Khách hỏi có phải lừa đảo không": "Khách nghi ngờ",
    "Khách lo lộ thông tin": "Khách nghi ngờ",
    "Khách hỏi em là người hay máy": "Hỏi về cuộc gọi",
    "Khách hỏi nghe máy có mất tiền không": "Hỏi về cuộc gọi",
    "Khách hỏi tư vấn có mất phí không": "Hỏi về cuộc gọi",
    "Khách hỏi nghe xong có bắt buộc đăng ký không": "Hỏi về cuộc gọi",
    "Khách phàn nàn bị gọi nhiều": "Khách khó chịu",
    "Khách hỏi sao gọi giờ này": "Khách khó chịu",
    "Khách đã được người khác tư vấn": "Khách khó chịu",
    "Gọi nhầm người": "Khách khó chịu",
    "Khách đã biết thông tin": "Khách muốn nghe tiếp",
    "Khách đồng ý nghe tiếp": "Khách muốn nghe tiếp",
    "Khách hỏi chung chung muốn biết thêm": "Khách muốn nghe tiếp",
    "Khách không còn câu hỏi": "Kết thúc cuộc gọi",
    "Khách chào kết thúc": "Kết thúc cuộc gọi",
}

BANG_MOI = [
    # ── Mở đầu cuộc gọi ────────────────────────────────────────────────────
    ("Mở đầu cuộc gọi", "Khách hỏi gọi có việc gì",
     ["em gọi anh có việc gì thế", "gọi chị có chuyện gì không em", "có việc gì em nói đi",
      "em gọi về việc gì vậy", "gọi anh làm gì đấy em"],
     "Dạ em gọi để giới thiệu nhanh chương trình ưu đãi của ngân hàng tới anh chị ạ. Anh chị cho em xin một phút được không ạ?"),
    ("Mở đầu cuộc gọi", "Khách hỏi mất bao lâu",
     ["có lâu không em", "nói mất bao lâu", "em nói nhanh thôi nhé", "anh chỉ có một phút thôi",
      "mất nhiều thời gian không em"],
     "Dạ em chỉ xin anh chị khoảng một phút thôi ạ. Em nói ngắn gọn những điểm chính, anh chị thấy cần thì mình trao đổi thêm ạ."),
    ("Mở đầu cuộc gọi", "Khách cho phép nói nhanh",
     ["ừ em nói nhanh đi", "được em nói đi", "rồi em nói thử xem", "ừ anh nghe đây", "nói đi chị nghe"],
     "Dạ em cảm ơn anh chị ạ. Anh chị quan tâm tới phần nào nhất, để em nói ngay vào phần đó ạ?"),
    ("Mở đầu cuộc gọi", "Khách hỏi chương trình gì",
     ["chương trình gì vậy em", "ưu đãi gì thế", "bên em đang có gì", "sản phẩm gì vậy em",
      "em giới thiệu cái gì đấy"],
     "Dạ đây là chương trình ưu đãi ngân hàng đang dành cho khách hàng ạ. Anh chị muốn nghe trước về lãi suất, hạn mức hay hồ sơ thủ tục ạ?"),
    ("Mở đầu cuộc gọi", "Khách hỏi có đúng là ngân hàng gọi không",
     ["có đúng ngân hàng gọi không đấy", "em gọi từ ngân hàng thật à", "số này là của ngân hàng à",
      "sao biết em là người của ngân hàng", "em có đúng nhân viên ngân hàng không"],
     "Dạ em gọi từ bộ phận tư vấn của ngân hàng ạ. Anh chị có thể gọi tổng đài chính thức của ngân hàng để kiểm tra lại bất cứ lúc nào ạ."),
    ("Mở đầu cuộc gọi", "Khách hỏi lấy thông tin ở đâu",
     ["em lấy thông tin của anh ở đâu", "ai đưa thông tin của chị cho em", "sao em có thông tin của anh",
      "thông tin của chị em lấy từ đâu ra"],
     "Dạ số của anh chị nằm trong danh sách khách hàng đã đồng ý nhận tư vấn của bên em ạ. Nếu anh chị không muốn nhận nữa, em xin ghi nhận ngay ạ."),
    ("Mở đầu cuộc gọi", "Khách đang nghe thử",
     ["thì em cứ nói thử xem nào", "nói thử nghe coi", "em trình bày đi", "ừ thử nói xem sao",
      "em cứ giới thiệu đi anh nghe thử"],
     "Dạ vâng ạ. Em nói ngắn gọn các điểm chính, chỗ nào anh chị muốn hỏi kỹ hơn thì anh chị cứ ngắt lời em ạ."),

    # ── Khách bận / hẹn lại ───────────────────────────────────────────────
    ("Khách bận", "Khách đang lái xe",
     ["anh đang lái xe", "chị đang đi đường", "anh đang chạy xe ngoài đường", "đang đi xe em ơi",
      "anh đang trên xe không nghe được"],
     "Dạ vậy anh chị tập trung lái xe cho an toàn ạ. Em xin phép liên hệ lại vào lúc khác, em chào anh chị ạ."),
    ("Khách bận", "Khách đang họp hoặc làm việc",
     ["anh đang họp", "chị đang làm việc", "đang trong giờ làm em ơi", "anh đang bận việc cơ quan",
      "chị đang có khách"],
     "Dạ em xin lỗi đã làm phiền lúc anh chị đang bận ạ. Anh chị cho em xin khung giờ tiện hơn để em liên hệ lại ạ?"),
    ("Khách bận", "Khách đang ăn cơm hoặc nghỉ ngơi",
     ["anh đang ăn cơm", "chị đang nghỉ trưa", "đang giờ ăn em ơi", "anh đang ngủ", "chị đang nghỉ ngơi"],
     "Dạ em xin lỗi đã gọi vào giờ nghỉ của anh chị ạ. Em xin phép liên hệ lại sau, anh chị tiện vào khoảng mấy giờ ạ?"),
    ("Khách bận", "Khách đang chăm con hoặc việc nhà",
     ["chị đang cho con ăn", "anh đang đón con", "chị đang bận con nhỏ", "đang dở việc nhà em ơi",
      "anh đang trông cháu"],
     "Dạ vâng ạ, anh chị cứ lo việc gia đình trước ạ. Em xin phép gọi lại lúc khác, khoảng mấy giờ thì tiện cho anh chị ạ?"),
    ("Khách bận", "Khách bảo gọi lại buổi tối",
     ["tối gọi lại cho anh", "em gọi lại buổi tối nhé", "tối chị mới rảnh", "sau giờ làm em gọi lại",
      "tối nay gọi lại đi em"],
     "Dạ vâng ạ, em xin ghi nhận là anh chị tiện nghe máy vào buổi tối. Em cảm ơn anh chị, em chào anh chị ạ."),
    ("Khách bận", "Khách bảo gọi lại ngày mai",
     ["mai gọi lại cho anh", "ngày mai em gọi lại nhé", "mai chị rảnh hơn", "để mai đi em",
      "hôm nay anh bận mai gọi lại"],
     "Dạ vâng ạ, em xin ghi nhận để bên em liên hệ lại anh chị vào ngày mai. Em cảm ơn anh chị ạ."),
    ("Khách bận", "Khách bảo gọi lại cuối tuần",
     ["cuối tuần gọi lại cho anh", "thứ bảy chủ nhật chị mới rảnh", "cuối tuần em gọi lại nhé",
      "để cuối tuần đi em"],
     "Dạ vâng ạ, em xin ghi nhận là anh chị tiện vào cuối tuần. Em cảm ơn anh chị đã nghe máy ạ."),
    ("Khách bận", "Khách bảo lúc khác",
     ["lúc khác đi em", "để khi khác nhé", "bữa khác em gọi lại", "hôm khác đi", "khi nào rảnh anh nghe"],
     "Dạ vâng ạ. Em xin phép liên hệ lại vào dịp khác, anh chị thường tiện nghe máy vào buổi nào ạ?"),
    ("Khách bận", "Khách bảo sẽ tự gọi lại",
     ["để anh gọi lại sau", "khi nào cần chị gọi", "có gì anh liên hệ lại", "để chị chủ động gọi lại",
      "cần thì anh gọi"],
     "Dạ vâng ạ. Khi nào tiện, anh chị liên hệ lại tổng đài của ngân hàng để được hỗ trợ ạ. Em cảm ơn anh chị ạ."),
    ("Khách bận", "Khách đang ở chỗ ồn",
     ["chỗ anh đang ồn lắm", "ở đây ồn quá không nghe được", "chị đang ở ngoài chợ", "anh đang ở công trường",
      "xung quanh ồn quá em ơi"],
     "Dạ vâng ạ, chỗ anh chị đang ồn thì khó trao đổi kỹ ạ. Em xin phép gọi lại lúc anh chị ở chỗ yên tĩnh hơn ạ."),

    # ── Khách từ chối ─────────────────────────────────────────────────────
    ("Khách từ chối", "Khách không có nhu cầu",
     ["anh không có nhu cầu đâu", "chị không cần đâu em", "anh chưa cần vay", "không có nhu cầu em nhé",
      "chị không dùng tới đâu"],
     "Dạ em hiểu ạ. Em cảm ơn anh chị đã nghe máy, khi nào có nhu cầu anh chị cứ liên hệ ngân hàng ạ."),
    ("Khách từ chối", "Khách đã dùng sản phẩm nơi khác",
     ["anh dùng bên ngân hàng khác rồi", "chị có thẻ bên khác rồi", "anh đang vay bên kia rồi",
      "chị gửi tiền ở chỗ khác rồi", "anh quen dùng ngân hàng khác rồi"],
     "Dạ vâng ạ, anh chị đang dùng bên khác thì vẫn có thể tham khảo thêm để so sánh ạ. Anh chị có muốn nghe nhanh điểm khác biệt không ạ?"),
    ("Khách từ chối", "Khách không thích vay nợ",
     ["anh không thích vay mượn", "chị sợ nợ lắm", "anh không muốn mắc nợ", "nhà chị không vay bao giờ",
      "vay rồi lại lo trả mệt lắm"],
     "Dạ em hiểu ạ, cân nhắc kỹ trước khi vay là đúng ạ. Em chỉ gửi thông tin để anh chị tham khảo, không có gì ràng buộc ạ."),
    ("Khách từ chối", "Khách bảo đừng gọi nữa",
     ["đừng gọi cho anh nữa", "em xóa số chị đi", "lần sau đừng gọi nữa nhé", "anh không muốn nhận cuộc gọi này nữa",
      "đưa số anh ra khỏi danh sách đi"],
     "Dạ em xin lỗi đã làm phiền anh chị ạ. Em xin ghi nhận yêu cầu để bên em không liên hệ lại nữa. Em chào anh chị ạ."),
    ("Khách từ chối", "Khách không tin tư vấn qua điện thoại",
     ["anh không làm gì qua điện thoại đâu", "chị không tin mấy cuộc gọi này", "có gì anh ra ngân hàng",
      "chị chỉ làm việc trực tiếp thôi", "qua điện thoại anh không yên tâm"],
     "Dạ anh chị cẩn thận như vậy là đúng ạ. Em chỉ giới thiệu thông tin, mọi thủ tục anh chị có thể đến trực tiếp chi nhánh ngân hàng để làm ạ."),
    ("Khách từ chối", "Khách từ chối thẳng",
     ["không em ơi", "thôi không cần đâu", "không nhé em", "anh không nghe đâu", "chị không quan tâm đâu"],
     "Dạ vâng ạ. Em cảm ơn anh chị đã nghe máy, em xin phép không làm phiền thêm. Em chào anh chị ạ."),
    ("Khách từ chối", "Khách bảo không đủ điều kiện",
     ["chắc anh không đủ điều kiện đâu", "chị làm gì đủ điều kiện", "như anh thì ai cho vay",
      "chị nghĩ mình không được duyệt đâu"],
     "Dạ việc đủ điều kiện hay không phải qua thẩm định hồ sơ mới biết được ạ. Nếu anh chị muốn, em xin ghi nhận để chuyên viên kiểm tra cụ thể giúp ạ."),
    ("Khách từ chối", "Khách bảo đã có đủ tiền",
     ["anh có tiền rồi không cần vay", "nhà chị đủ dùng rồi", "anh không thiếu tiền", "chị không cần thêm vốn"],
     "Dạ vâng ạ, vậy thì tốt quá ạ. Em cảm ơn anh chị đã nghe máy, khi nào cần thêm thông tin anh chị cứ liên hệ ngân hàng ạ."),

    # ── Khách phân vân ────────────────────────────────────────────────────
    ("Khách phân vân", "Khách muốn tìm hiểu thêm đã",
     ["để anh tìm hiểu thêm đã", "chị cần xem thêm thông tin", "anh muốn đọc kỹ đã", "để chị nghiên cứu thêm",
      "anh chưa rõ lắm cần tìm hiểu"],
     "Dạ vâng ạ, anh chị cứ tìm hiểu kỹ ạ. Anh chị đang chưa rõ điểm nào, em giải thích thêm ngay phần đó ạ?"),
    ("Khách phân vân", "Khách sợ rắc rối thủ tục",
     ["thủ tục chắc rắc rối lắm", "anh ngại giấy tờ lắm", "làm hồ sơ mệt lắm", "chị sợ thủ tục lằng nhằng",
      "giấy tờ nhiều lắm phải không"],
     "Dạ em hiểu ạ, nhiều anh chị cũng ngại thủ tục. Hồ sơ cần những gì em có thể nói rõ từng món để anh chị dễ chuẩn bị ạ."),
    ("Khách phân vân", "Khách sợ không trả nổi",
     ["anh sợ không trả nổi", "chị lo không trả được", "vay rồi không biết có trả nổi không",
      "thu nhập của anh bấp bênh sợ không kham được"],
     "Dạ anh chị cân nhắc khả năng trả nợ trước khi vay là rất đúng ạ. Anh chị nên tính số tiền trả mỗi tháng so với thu nhập rồi hãy quyết định ạ."),
    ("Khách phân vân", "Khách muốn so sánh với nơi khác",
     ["để anh so sánh với bên khác đã", "chị muốn hỏi thêm vài ngân hàng", "anh cần so với chỗ khác",
      "để chị tham khảo thêm bên khác"],
     "Dạ vâng ạ, anh chị so sánh vài nơi rồi chọn là hợp lý ạ. Anh chị cần em nói rõ lại thông tin nào để tiện so sánh không ạ?"),
    ("Khách phân vân", "Khách chưa cần ngay nhưng sau này có thể",
     ["sau này có thể anh cần", "để vài tháng nữa xem", "cuối năm chị mới tính", "bao giờ cần anh sẽ hỏi",
      "hiện giờ chưa nhưng sau có thể cần"],
     "Dạ vâng ạ. Anh chị cứ lưu lại thông tin, khi nào tới lúc cần anh chị liên hệ ngân hàng để được tư vấn theo chương trình khi đó ạ."),
    ("Khách phân vân", "Khách hỏi nên chọn thế nào",
     ["theo em anh nên chọn thế nào", "em thấy chị nên làm không", "em khuyên anh sao", "nếu là em thì em có làm không",
      "em tư vấn anh nên quyết thế nào"],
     "Dạ quyết định là ở anh chị ạ, em chỉ cung cấp thông tin để anh chị cân nhắc. Anh chị nên đối chiếu nhu cầu và khả năng chi trả của mình ạ."),
    ("Khách phân vân", "Khách bảo để xem đã",
     ["để anh xem đã", "để chị tính đã", "từ từ để anh xem", "chị chưa biết để xem sao", "cứ để đấy anh tính"],
     "Dạ vâng ạ, anh chị cứ thong thả cân nhắc ạ. Trong lúc đó anh chị còn muốn hỏi thêm em phần nào không ạ?"),
    ("Khách phân vân", "Khách bảo đang tính việc khác",
     ["anh đang lo việc khác", "dạo này chị nhiều việc quá", "anh đang tính chuyện khác chưa nghĩ tới cái này",
      "giờ chị chưa có tâm trí nghĩ tới"],
     "Dạ em hiểu ạ. Vậy em không làm phiền thêm, khi nào anh chị thu xếp được thì liên hệ ngân hàng để được tư vấn ạ."),

    # ── Khách nghi ngờ ────────────────────────────────────────────────────
    ("Khách nghi ngờ", "Khách sợ bị lấy cắp thông tin",
     ["em có lấy thông tin của anh đi bán không", "chị sợ bị lộ số điện thoại", "thông tin của anh rồi lại bị bán",
      "nghe xong lại bị người khác gọi làm phiền"],
     "Dạ thông tin của anh chị chỉ dùng để tư vấn theo quy định của ngân hàng ạ. Em không yêu cầu anh chị cung cấp mật khẩu hay mã xác thực nào ạ."),
    ("Khách nghi ngờ", "Khách hỏi có phải chuyển tiền trước không",
     ["có phải chuyển tiền trước không", "có phải đóng phí trước mới được không", "anh có phải nộp tiền gì trước không",
      "bên em có bắt chuyển khoản trước không"],
     "Dạ em không yêu cầu anh chị chuyển tiền trước qua điện thoại ạ. Ai yêu cầu chuyển tiền trước để được duyệt vay thì anh chị nên cảnh giác ạ."),
    ("Khách nghi ngờ", "Khách hỏi có phải đọc mã OTP không",
     ["em có cần mã OTP của anh không", "có phải đọc mã xác thực không", "chị có phải đưa mật khẩu không",
      "em có hỏi mã gửi về điện thoại không"],
     "Dạ không ạ. Ngân hàng không bao giờ yêu cầu anh chị đọc mật khẩu hay mã xác thực qua điện thoại, anh chị không cung cấp cho bất kỳ ai ạ."),
    ("Khách nghi ngờ", "Khách bảo dạo này nhiều lừa đảo",
     ["dạo này lừa đảo nhiều lắm", "bây giờ toàn lừa đảo qua điện thoại", "anh bị lừa một lần rồi",
      "chị nghe nói giả danh ngân hàng nhiều lắm"],
     "Dạ đúng là anh chị nên cảnh giác ạ. Em chỉ giới thiệu thông tin, anh chị có thể gọi tổng đài chính thức hoặc đến chi nhánh để kiểm tra lại ạ."),
    ("Khách nghi ngờ", "Khách muốn kiểm tra lại với ngân hàng",
     ["để anh gọi tổng đài hỏi lại", "chị sẽ ra ngân hàng hỏi lại", "anh kiểm tra lại đã", "để chị xác minh đã"],
     "Dạ vâng ạ, anh chị kiểm tra lại qua tổng đài chính thức hoặc tại chi nhánh là hoàn toàn nên làm ạ. Em cảm ơn anh chị ạ."),
    ("Khách nghi ngờ", "Khách nghi có chi phí ẩn",
     ["chắc lại có phí ẩn chứ gì", "nói thế chứ kiểu gì cũng có phí", "có bẫy gì trong đó không",
      "đằng sau có điều kiện gì không em"],
     "Dạ mọi khoản phí và điều kiện đều được ghi rõ trong hợp đồng ạ. Anh chị nên đọc kỹ hợp đồng và hỏi lại chỗ chưa rõ trước khi ký ạ."),
    ("Khách nghi ngờ", "Khách bảo quảng cáo thì hay lắm",
     ["quảng cáo thì nói hay lắm", "bên nào chả nói tốt", "nói thì dễ lắm", "tư vấn thì bao giờ chẳng hay"],
     "Dạ em hiểu ạ. Vì vậy anh chị nên xem các điều khoản ghi trong hợp đồng, đó mới là căn cứ chính thức để anh chị quyết định ạ."),

    # ── Hỏi về cuộc gọi ───────────────────────────────────────────────────
    ("Hỏi về cuộc gọi", "Khách hỏi cuộc gọi có ghi âm không",
     ["cuộc gọi này có ghi âm không", "em có ghi âm lại không", "nói chuyện này có bị thu âm không"],
     "Dạ cuộc gọi có thể được ghi âm để ngân hàng kiểm tra chất lượng tư vấn ạ."),
    ("Hỏi về cuộc gọi", "Khách muốn gặp người thật",
     ["cho anh gặp nhân viên thật", "chị muốn nói chuyện với người", "nối máy cho người phụ trách đi",
      "anh muốn nói chuyện với chuyên viên", "có ai là người thật không cho chị gặp"],
     "Dạ vâng ạ, em xin ghi nhận yêu cầu để chuyên viên của ngân hàng liên hệ trực tiếp với anh chị ạ."),
    ("Hỏi về cuộc gọi", "Khách hỏi số tổng đài",
     ["số tổng đài bên em là bao nhiêu", "cho anh xin số hotline", "chị muốn gọi lại thì gọi số nào",
      "có số nào để anh liên hệ lại không"],
     "Dạ anh chị liên hệ qua số tổng đài chính thức in trên thẻ hoặc trên trang web của ngân hàng ạ. Em xin ghi nhận để chuyên viên liên hệ lại anh chị ạ."),
    ("Hỏi về cuộc gọi", "Khách hỏi chi nhánh ở đâu",
     ["chi nhánh bên em ở đâu", "gần nhà anh có chi nhánh nào không", "chị muốn ra quầy thì ra đâu",
      "ngân hàng mình có phòng giao dịch ở đâu"],
     "Dạ anh chị xem địa chỉ chi nhánh gần nhất trên trang web chính thức của ngân hàng ạ. Em xin ghi nhận để chuyên viên hướng dẫn cụ thể cho anh chị ạ."),
    ("Hỏi về cuộc gọi", "Khách hỏi có gửi thông tin qua tin nhắn không",
     ["em gửi thông tin qua tin nhắn cho anh", "nhắn cho chị đọc được không", "có tài liệu gì gửi anh xem",
      "em gửi qua zalo cho chị", "gửi mail cho anh đi"],
     "Dạ em xin ghi nhận yêu cầu nhận thông tin bằng văn bản của anh chị để chuyên viên liên hệ gửi lại ạ."),
    ("Hỏi về cuộc gọi", "Khách hỏi em làm ở bộ phận nào",
     ["em làm ở bộ phận nào", "em thuộc phòng nào", "em là nhân viên chi nhánh nào",
      "em làm ở đâu trong ngân hàng"],
     "Dạ em thuộc bộ phận tư vấn khách hàng qua điện thoại của ngân hàng ạ."),
    ("Hỏi về cuộc gọi", "Khách hỏi thông tin em nói có chắc không",
     ["em nói có chắc không đấy", "thông tin này có chính xác không", "em có nói đúng không",
      "sau này có đúng như em nói không"],
     "Dạ em tư vấn theo thông tin sản phẩm ngân hàng đang công bố ạ. Điều khoản chính thức là nội dung ghi trong hợp đồng anh chị ký ạ."),
    ("Hỏi về cuộc gọi", "Khách hỏi giờ làm việc",
     ["bên em làm việc đến mấy giờ", "ngân hàng mở cửa giờ nào", "thứ bảy bên em có làm không",
      "mấy giờ anh ra ngân hàng được"],
     "Dạ giờ làm việc của từng chi nhánh anh chị xem trên trang web chính thức của ngân hàng ạ. Em xin ghi nhận để chuyên viên hỗ trợ thêm cho anh chị ạ."),

    # ── Khách khó chịu ────────────────────────────────────────────────────
    ("Khách khó chịu", "Khách nổi nóng",
     ["phiền quá đi mất", "bực mình quá", "làm phiền người ta quá", "gọi gì mà lắm thế không biết",
      "anh đang bực đừng gọi"],
     "Dạ em thành thật xin lỗi vì đã làm phiền anh chị ạ. Em xin phép dừng cuộc gọi tại đây, em chào anh chị ạ."),
    ("Khách khó chịu", "Khách bảo đã từ chối nhiều lần",
     ["anh nói không cần bao nhiêu lần rồi", "chị từ chối mấy lần rồi mà", "đã bảo không cần rồi còn gọi",
      "lần trước anh nói không rồi mà"],
     "Dạ em xin lỗi anh chị ạ. Em xin ghi nhận ngay để bên em không liên hệ lại về chương trình này nữa ạ."),
    ("Khách khó chịu", "Khách dọa khiếu nại",
     ["anh sẽ khiếu nại đấy", "chị báo lên ngân hàng cho mà xem", "còn gọi nữa anh phản ánh đấy",
      "chị sẽ báo cáo số này"],
     "Dạ em xin lỗi vì đã để anh chị không hài lòng ạ. Em xin ghi nhận phản ánh của anh chị và sẽ không liên hệ làm phiền thêm ạ."),
    ("Khách khó chịu", "Khách chê tư vấn dở",
     ["em tư vấn chán quá", "nói mãi không vào trọng tâm", "em nói vòng vo quá", "tư vấn gì mà khó hiểu thế"],
     "Dạ em xin lỗi vì em trình bày chưa rõ ạ. Anh chị cần biết nhất điểm nào, em trả lời thẳng vào điểm đó ạ?"),
    ("Khách khó chịu", "Khách bảo nói nhiều quá",
     ["em nói nhiều quá", "nói ngắn thôi em", "dài dòng quá", "tóm lại là sao", "nói gọn lại đi em"],
     "Dạ em xin lỗi ạ, em sẽ nói ngắn gọn hơn. Anh chị muốn biết ngay về lãi suất, hạn mức hay hồ sơ ạ?"),
    ("Khách khó chịu", "Khách phàn nàn dịch vụ ngân hàng",
     ["ngân hàng bên em làm ăn chán lắm", "anh từng bị bên em làm khó", "dịch vụ bên em tệ lắm",
      "chị không hài lòng với ngân hàng này"],
     "Dạ em rất tiếc vì anh chị đã có trải nghiệm chưa tốt ạ. Em xin ghi nhận phản ánh này để chuyển tới bộ phận phụ trách ạ."),
    ("Khách khó chịu", "Khách bảo gọi không đúng lúc",
     ["gọi không đúng lúc gì cả", "sao lại gọi lúc này", "đang dở việc mà gọi", "gọi lúc người ta đang bận"],
     "Dạ em xin lỗi đã gọi không đúng lúc ạ. Em xin phép liên hệ lại sau, khoảng mấy giờ thì tiện cho anh chị ạ?"),

    # ── Trục trặc nghe nói ────────────────────────────────────────────────
    ("Trục trặc nghe nói", "Khách bảo nói lại",
     ["em nói lại đi", "nhắc lại giúp anh", "em vừa nói gì cơ", "nói lại câu vừa rồi xem", "chị chưa nghe kịp"],
     "Dạ vâng ạ. Anh chị chưa nghe kịp phần nào, lãi suất, hạn mức hay hồ sơ, để em nói lại đúng phần đó ạ?"),
    ("Trục trặc nghe nói", "Khách alo vì mất tiếng",
     ["alo em còn đó không", "alo alo có nghe không", "sao im thế em", "em ơi còn nghe máy không",
      "mất tiếng rồi à"],
     "Dạ em vẫn đang nghe máy ạ. Anh chị nói tiếp giúp em ạ."),
    ("Trục trặc nghe nói", "Khách bảo tiếng bị ngắt quãng",
     ["tiếng em bị ngắt quãng", "nghe chập chờn quá", "tiếng cứ bị đứt", "nghe câu được câu mất",
      "em nói bị rè quá"],
     "Dạ em xin lỗi vì đường truyền chưa ổn ạ. Em nói lại chậm và rõ hơn, anh chị nghe được em chưa ạ?"),
    ("Trục trặc nghe nói", "Khách bảo nói to lên",
     ["nói to lên em", "em nói lớn lên chút", "to tiếng lên anh mới nghe", "chị nặng tai em nói to lên"],
     "Dạ vâng ạ, em nói to và rõ hơn ạ. Anh chị nghe được em chưa ạ?"),
    ("Trục trặc nghe nói", "Khách cần lấy giấy bút",
     ["chờ anh lấy giấy bút", "đợi chị ghi lại đã", "để anh lấy cái bút", "em chờ chị lấy sổ ghi"],
     "Dạ vâng ạ, em chờ máy. Khi nào anh chị sẵn sàng thì báo em ạ."),
    ("Trục trặc nghe nói", "Khách quay lại sau khi chờ",
     ["rồi em nói tiếp đi", "anh nghe đây em nói đi", "xong rồi em nói đi", "chị quay lại rồi đây"],
     "Dạ vâng ạ. Mình trao đổi tiếp nhé, anh chị muốn em nói tiếp về phần nào ạ?"),
    ("Trục trặc nghe nói", "Khách hỏi em có nghe không",
     ["em có nghe anh nói không", "em nghe rõ chị không", "anh nói em nghe được không"],
     "Dạ em nghe rõ ạ. Anh chị cứ nói tiếp ạ."),

    # ── Khách muốn nghe tiếp ──────────────────────────────────────────────
    ("Khách muốn nghe tiếp", "Khách tỏ ra quan tâm",
     ["nghe cũng được đấy", "cũng hay đấy em", "anh thấy cũng ổn", "chị cũng đang cần", "nghe có vẻ được"],
     "Dạ em cảm ơn anh chị ạ. Anh chị muốn em nói kỹ hơn về lãi suất, hạn mức hay hồ sơ thủ tục trước ạ?"),
    ("Khách muốn nghe tiếp", "Khách muốn đăng ký",
     ["anh muốn đăng ký", "làm cho chị đi", "vậy anh đăng ký thế nào", "chị muốn làm hồ sơ",
      "ok em làm cho anh"],
     "Dạ vâng ạ. Em xin ghi nhận nhu cầu của anh chị để chuyên viên ngân hàng liên hệ hướng dẫn hồ sơ ạ."),
    ("Khách muốn nghe tiếp", "Khách hỏi bước tiếp theo",
     ["thế giờ anh phải làm gì", "bước tiếp theo là gì em", "tiếp theo chị làm thế nào", "rồi sau đó thì sao"],
     "Dạ bước tiếp theo là em ghi nhận nhu cầu của anh chị để chuyên viên liên hệ hướng dẫn chuẩn bị hồ sơ ạ."),
    ("Khách muốn nghe tiếp", "Khách muốn nghe lại từ đầu",
     ["em nói lại từ đầu đi", "em giới thiệu lại xem nào", "nãy giờ anh chưa nghe kỹ em nói lại",
      "chị mới nghe được một nửa"],
     "Dạ vâng ạ. Em nói lại ngắn gọn nhé, anh chị muốn em bắt đầu từ lãi suất, hạn mức hay hồ sơ ạ?"),
    ("Khách muốn nghe tiếp", "Khách hỏi còn gì nữa không",
     ["còn gì nữa không em", "thế thôi à", "còn ưu điểm gì nữa", "hết chưa em", "còn thông tin gì nữa không"],
     "Dạ em đã nói các điểm chính rồi ạ. Anh chị còn băn khoăn phần nào, em giải thích thêm phần đó ạ?"),
    ("Khách muốn nghe tiếp", "Khách muốn giới thiệu cho người quen",
     ["để anh giới thiệu cho bạn anh", "chị có người quen đang cần", "anh nói với người nhà anh xem",
      "em tư vấn cho em gái chị được không"],
     "Dạ em cảm ơn anh chị ạ. Người quen của anh chị có thể liên hệ tổng đài ngân hàng để được tư vấn trực tiếp ạ."),
    ("Khách muốn nghe tiếp", "Khách ậm ừ đồng ý",
     ["ừ được", "ừ thế cũng được", "vâng em", "ờ ờ", "ừ anh hiểu rồi"],
     "Dạ vâng ạ. Anh chị còn muốn hỏi thêm em phần nào nữa không ạ?"),

    # ── Xã giao ───────────────────────────────────────────────────────────
    ("Xã giao", "Khách hỏi thăm sức khỏe",
     ["em khỏe không", "dạo này em thế nào", "em có mệt không", "làm việc có vất vả không em"],
     "Dạ em cảm ơn anh chị đã hỏi thăm ạ. Em xin phép quay lại phần thông tin để hỗ trợ anh chị ạ."),
    ("Xã giao", "Khách hỏi ăn cơm chưa",
     ["em ăn cơm chưa", "ăn uống gì chưa em", "trưa rồi em ăn chưa"],
     "Dạ em cảm ơn anh chị đã quan tâm ạ. Anh chị còn cần em hỗ trợ thêm thông tin nào không ạ?"),
    ("Xã giao", "Khách chúc",
     ["chúc em làm việc tốt nhé", "chúc em một ngày tốt lành", "chúc em may mắn", "em làm việc vui vẻ nhé"],
     "Dạ em cảm ơn anh chị ạ. Em cũng chúc anh chị một ngày nhiều niềm vui ạ."),
    ("Xã giao", "Khách trêu đùa",
     ["em nói như đọc bài ấy", "em nói như cái máy", "giọng em nghe như robot", "em đọc thuộc lòng à"],
     "Dạ em xin lỗi nếu em nói chưa tự nhiên ạ. Anh chị cứ hỏi điều mình quan tâm, em trả lời thẳng vào đó ạ."),
    ("Xã giao", "Khách thông cảm cho tư vấn viên",
     ["anh biết em cũng vất vả", "chị hiểu công việc của em", "làm nghề này cũng khổ nhỉ",
      "em cũng chỉ làm nhiệm vụ thôi"],
     "Dạ em cảm ơn anh chị đã thông cảm ạ. Em xin phép không làm mất thêm thời gian của anh chị ạ."),
    ("Xã giao", "Khách xin lỗi",
     ["anh xin lỗi nhé", "chị xin lỗi vì nói hơi nặng", "ngại quá em thông cảm", "xin lỗi em anh đang vội"],
     "Dạ không sao đâu ạ. Em cảm ơn anh chị, khi nào tiện mình trao đổi tiếp ạ."),
    ("Xã giao", "Khách hỏi chuyện ngoài lề",
     ["hôm nay trời nóng nhỉ", "chỗ em có mưa không", "em xem bóng đá không", "dạo này giá cả đắt đỏ quá"],
     "Dạ vâng ạ. Em xin phép quay lại phần thông tin sản phẩm để hỗ trợ anh chị cho đúng việc ạ."),

    # ── Kết thúc cuộc gọi ─────────────────────────────────────────────────
    ("Kết thúc cuộc gọi", "Khách bảo vậy nhé",
     ["thế nhé em", "vậy nhé", "thế đã em nhé", "ok thế nhé", "vậy thôi nhé em"],
     "Dạ vâng ạ. Em cảm ơn anh chị đã dành thời gian nghe máy, em chào anh chị ạ."),
    ("Kết thúc cuộc gọi", "Khách bảo có gì sẽ liên hệ",
     ["có gì anh liên hệ sau", "cần thì chị gọi lại", "khi nào cần anh sẽ tìm em", "có nhu cầu chị báo"],
     "Dạ vâng ạ. Khi nào cần, anh chị liên hệ tổng đài ngân hàng để được hỗ trợ ạ. Em chào anh chị ạ."),
    ("Kết thúc cuộc gọi", "Khách phải đi",
     ["anh phải đi rồi", "chị có việc phải đi", "anh bận rồi nhé", "thôi chị đi đây", "anh có khách rồi"],
     "Dạ vâng ạ, em không làm phiền anh chị nữa. Em cảm ơn anh chị, em chào anh chị ạ."),
    ("Kết thúc cuộc gọi", "Khách cảm ơn và kết thúc",
     ["cảm ơn em thế nhé", "ok cảm ơn em chào em", "cảm ơn em đã tư vấn", "anh cảm ơn nhé thế thôi"],
     "Dạ em cảm ơn anh chị đã lắng nghe ạ. Em chúc anh chị một ngày tốt lành, em chào anh chị ạ."),
    ("Kết thúc cuộc gọi", "Khách bảo đã rõ hết",
     ["anh rõ hết rồi", "chị hiểu rồi", "thông tin thế là đủ rồi", "anh nắm được rồi"],
     "Dạ vâng ạ. Nếu sau này anh chị cần hỏi thêm, anh chị liên hệ tổng đài ngân hàng ạ. Em chào anh chị ạ."),
    ("Kết thúc cuộc gọi", "Khách bảo để lúc khác bàn tiếp",
     ["để lúc khác bàn tiếp", "hôm khác nói tiếp nhé", "mình trao đổi sau nhé em", "lần sau nói tiếp"],
     "Dạ vâng ạ, em xin ghi nhận để bên em liên hệ lại anh chị vào dịp khác. Em cảm ơn anh chị ạ."),
]
